# Generated by Django 3.2.3 on 2021-06-03 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип транспортного средства',
                'verbose_name_plural': 'Типы транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Odometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Период пробегов',
                'verbose_name_plural': 'Периоды пробегов',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('phone', models.CharField(blank=True, default='', max_length=200, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=200, verbose_name='Email')),
                ('last_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, default='', max_length=1000, verbose_name='Имя')),
                ('surname_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='Отчество')),
                ('automarka', models.CharField(blank=True, default='', max_length=200, verbose_name='Марка автомобиля')),
                ('automodel', models.CharField(blank=True, default='', max_length=200, verbose_name='Модель автомобиля')),
                ('autogv', models.CharField(blank=True, default='', max_length=200, verbose_name='Год выпуска автомобиля')),
                ('autonumber', models.CharField(blank=True, default='', max_length=200, verbose_name='Гос номер автомобиля')),
                ('auto_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.autotype', verbose_name='Тип транспортного средства')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.country', verbose_name='Страна')),
                ('district', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.district', verbose_name='Район проживания')),
                ('odometer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.odometer', verbose_name='Пробег в месяц')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAutoRearView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_rear_view', models.ImageField(blank=True, null=True, upload_to='photo_auto_rear_view', verbose_name='Фото автомобиля сзади')),
                ('user_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля сзади',
                'verbose_name_plural': 'Фотографии автомобиля сзади',
            },
        ),
        migrations.CreateModel(
            name='PhotoAutoGeneralView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_general_view', models.ImageField(blank=True, null=True, upload_to='photo_auto_general_view', verbose_name='Фото общего вида автомобиля')),
                ('user_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фотография общего вида',
                'verbose_name_plural': 'Фотографии общего вида',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.country', verbose_name='Страна'),
        ),
    ]
