# Generated by Django 3.2.3 on 2021-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Администратор'), (2, 'Клиент'), (3, 'Рекламодатель'), (4, 'Кассир')], default=0, verbose_name='Роль пользователя'),
        ),
    ]
