# Generated by Django 3.2.3 on 2021-06-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_userprofile_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='user_email',
        ),
    ]
