# Generated by Django 3.2.3 on 2021-06-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_email_userprofile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auto_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.autotype', verbose_name='Тип транспортного средства'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.district', verbose_name='Район проживания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='odometer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.odometer', verbose_name='Пробег в месяц'),
        ),
    ]
