# Generated by Django 3.2.3 on 2021-06-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_advertiser_owner_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_auto_20210623_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_email',
        ),
        migrations.CreateModel(
            name='CampaignApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('application_status', models.IntegerField(choices=[(0, 'Нет'), (1, 'На одобрении'), (2, 'Одобрена'), (3, 'Отклонена'), (4, 'Отстранен от участия')], default=0, verbose_name='Статус заявки')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.campaign', verbose_name='Акция')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка в акцию',
                'verbose_name_plural': 'Заявки в акции',
            },
        ),
    ]
