# Generated by Django 3.2.3 on 2021-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210625_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignapplication',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'На одобрении'), (2, 'Одобрена'), (3, 'Отклонена'), (4, 'Отстранен от участия'), (5, 'На оклейке'), (6, 'Отказался от участия')], default=0, verbose_name='Статус заявки'),
        ),
    ]
