# Generated by Django 3.2.3 on 2021-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_campaignapplication_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignapplication',
            options={'ordering': ['-created_date'], 'verbose_name': 'Заявка в акцию', 'verbose_name_plural': 'Заявки в акции'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Как к вам обращаться?'),
        ),
    ]
