# Generated by Django 3.2.3 on 2021-07-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210706_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.ManyToManyField(blank=True, null=True, to='client.District', verbose_name='Районы присутствия'),
        ),
    ]
