# Generated by Django 3.2.3 on 2021-07-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20210706_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Марка транспортного средства',
                'verbose_name_plural': 'Марки транспортных средств',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='automarka',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='automodel',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.ManyToManyField(blank=True, to='client.District', verbose_name='Районы присутствия'),
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('marka', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.automarka', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель транспортного средства',
                'verbose_name_plural': 'Модели транспортных средств',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.automarka', verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.automodel', verbose_name='Модель автомобиля'),
        ),
    ]
