# Generated by Django 3.2.3 on 2021-07-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20210706_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('odometer', models.IntegerField(default=0, verbose_name='Текущий пробег')),
                ('photoreport_odometer', models.ImageField(upload_to='photoreport_odometer', verbose_name='Фотография одометра')),
                ('photoreport_sticker', models.ImageField(upload_to='photoreport_sticker', verbose_name='Фотография наклейки')),
                ('photoreport_status', models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'На одобрении'), (2, 'Одобрен'), (3, 'Отклонен')], default=0, verbose_name='Статус отчета')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фото отчет',
                'verbose_name_plural': 'Фото отчеты',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='automarka',
            options={'ordering': ['title'], 'verbose_name': 'Марка транспортного средства', 'verbose_name_plural': 'Марки транспортных средств'},
        ),
        migrations.AlterModelOptions(
            name='automodel',
            options={'ordering': ['title'], 'verbose_name': 'Модель транспортного средства', 'verbose_name_plural': 'Модели транспортных средств'},
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='approve_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема заявки'),
        ),
    ]
