# Generated by Django 3.2.3 on 2021-07-13 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_advertiser_owner_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0010_auto_20210713_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.advertiser', verbose_name='Рекламодатель'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.campaignapplication', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.campaign', verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='client',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'На одобрении'), (2, 'Одобрена'), (3, 'Отклонена'), (4, 'Отстранен от участия'), (5, 'На оклейке'), (6, 'Отказался от участия'), (7, 'Баллы перечислены на счет')], default=0, verbose_name='Статус заявки'),
        ),
    ]
