# Generated by Django 3.2.3 on 2021-07-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_advertiser_owner_user'),
        ('client', '0011_auto_20210713_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.advertiser', verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.campaign', verbose_name='Акция'),
        ),
    ]
