# Generated by Django 3.2.3 on 2021-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo', verbose_name='Логотип компании'),
        ),
    ]
