# Generated by Django 3.2.3 on 2021-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_companyprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='kassir_login',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Логин кассира'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='kassir_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль кассира'),
        ),
    ]
