# Generated by Django 3.2.3 on 2021-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20210715_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_rearview',
            field=models.ImageField(blank=True, null=True, upload_to='auto_rearview', verbose_name='Вид автомобиля сзади'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_sideview',
            field=models.ImageField(blank=True, null=True, upload_to='auto_sideview', verbose_name='Общий вид автомобиля'),
        ),
    ]
