# Generated by Django 3.2.3 on 2021-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20210716_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='admin_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий администратора для себя'),
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='sticker_reserve_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бронь времени на оклейку машины'),
        ),
    ]
