# Generated by Django 3.2.3 on 2021-08-06 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0017_auto_20210804_1603'),
        ('client', '0017_auto_20210727_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_increase', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Приход')),
                ('balance_decrease', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Расход')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баллов до корректировки')),
                ('balance_current', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баллов после корректировки')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата')),
                ('history_description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('change_type', models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение баллов'), (4, 'Списание за услугу или товар')], default=0, verbose_name='Тип')),
                ('advertiser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.advertiser', verbose_name='Рекламодатель')),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.campaign', verbose_name='Акция')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Движение баллов на балансе клиента',
                'verbose_name_plural': 'Движения баллов на балансе клиента',
            },
        ),
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баллов после корректировки')),
                ('advertiser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.advertiser', verbose_name='Рекламодатель')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Баланс клиента',
                'verbose_name_plural': 'Балансы клиентов',
            },
        ),
    ]
