# Generated by Django 3.2.3 on 2021-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_clientbalance_clientbalancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс баллов'),
        ),
    ]
