# Generated by Django 3.2.3 on 2021-08-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20210804_1603'),
        ('client', '0019_alter_clientbalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbalancehistory',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.campaign', verbose_name='Акция'),
        ),
    ]
