# Generated by Django 3.2.3 on 2021-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_alter_clientbalancehistory_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Телефон'),
        ),
    ]
