# Generated by Django 3.2.3 on 2022-02-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignapplication',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'На одобрении'), (2, 'Одобрена'), (3, 'Отклонена'), (4, 'Отстранен от участия'), (5, 'На оклейке'), (6, 'Отказался от участия после оклейки'), (7, 'Баллы перечислены на счет'), (8, 'Отказался от участия до оклейки')], default=0, verbose_name='Статус заявки'),
        ),
    ]
