# Generated by Django 3.2.3 on 2022-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_alter_campaignapplication_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_markamodel_other',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Марка и модель автомобиля'),
        ),
    ]
