# Generated by Django 3.2.3 on 2022-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_userprofile_auto_markamodel_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loaded_rsainfo_attempts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество попыток запроса информации из ГИБДД'),
        ),
    ]
