# Generated by Django 3.2.3 on 2022-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_userprofile_loaded_rsainfo_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gibdd_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация из ГИБДД'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rsa_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация из RSA'),
        ),
    ]
