version: '2'

services:
  db:
    image: postgres
    container_name: priliplo_db
    environment:
      - POSTGRES_USER=priliplo
      - POSTGRES_PASSWORD=priliplo
      - POSTGRES_DB=priliplo
    ports:
      - "5432:5432"
  web:
    build: .
#    command: pip install django-cron
#    command: python3 manage.py runserver 0.0.0.0:80
#    command: bash -c "pip install django_cron && pip install git+https://github.com/Zex0n/django-robokassa.git --force-reinstall && gunicorn priliplo.wsgi:application --bind 0.0.0.0:8000"
    command: gunicorn priliplo.wsgi:application --bind 0.0.0.0:8000 --timeout 60
#    command: python3 manage.py runserver 0.0.0.0:8000
#    command: python -m http.server 8000
    volumes:
      - .:/code
    container_name: priliplo_web
#    ports:
#      - "80:80"
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
#    command: cp /code/nginx/nginx.conf /etc/nginx/conf.d
#    command: ls /etc/nginx/conf.d/nginx.conf
    volumes:
      - .:/code
      - /etc/letsencrypt/live/priliplo.ru/fullchain.pem:/ssl/fullchain.pem
      - /etc/letsencrypt/live/priliplo.ru/privkey.pem:/ssl/privkey.pem
      - /etc/letsencrypt/live/priliplo.ru/chain.pem:/ssl/chain.pem
      - /etc/letsencrypt/live/lk.priliplo.ru/fullchain.pem:/ssl/lk/fullchain.pem
      - /etc/letsencrypt/live/lk.priliplo.ru/privkey.pem:/ssl/lk/privkey.pem
      - /etc/letsencrypt/live/lk.priliplo.ru/chain.pem:/ssl/lk/chain.pem
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
