# Generated by Django 3.2.3 on 2022-05-26 15:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('in_menus', models.BooleanField(blank=True, default=True, verbose_name='Опубликовать')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('menu_title', models.CharField(blank=True, help_text='Оставьте пустым для использования названия страницы', max_length=255, null=True, verbose_name='Название в меню')),
                ('slug', models.SlugField(blank=True, help_text="Только английские буквы, цифры и знаки минус и подчеркивание. <br><a id='set_main_page'>Главная страница</a>", unique=True, verbose_name='Имя для url')),
                ('login_required', models.BooleanField(default=False, help_text='Если выбрано, то только залогиненный пользователь может просматривать страницу', verbose_name='Требуется логин')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('page_type', models.IntegerField(choices=[(0, 'Страница'), (1, 'Ссылка')], default=0, verbose_name='Тип страницы')),
                ('redirect_url', models.CharField(blank=True, default='', max_length=1000, verbose_name='URL для редиректа')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
