# Generated by Django 3.2.3 on 2025-08-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='page.page'),
        ),
    ]
