# Generated by Django 3.2.3 on 2025-08-09 09:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_slider_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('btn_text', models.CharField(blank=True, max_length=128, verbose_name='Текст кнопки')),
                ('btn_url', models.URLField(blank=True, max_length=512, verbose_name='URL кнопки')),
                ('img', models.ImageField(upload_to='sliders/%Y%m%d%s/', verbose_name='Картинка')),
                ('img_mob', models.ImageField(blank=True, upload_to='sliders/%Y%m%d%s/', verbose_name='Картинка для мобильных')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page.slider')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
