# Generated by Django 3.2.3 on 2025-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='img',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='img_mob',
        ),
        migrations.AlterField(
            model_name='slide',
            name='btn_url',
            field=models.SlugField(blank=True, max_length=512, verbose_name='URL кнопки'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=models.TextField(blank=True, max_length=512, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
