# Generated by Django 3.2.3 on 2025-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20250809_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='btn_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='URL кнопки'),
        ),
    ]
