# Generated by Django 3.2.3 on 2025-08-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_slide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='img',
            field=models.ImageField(blank=True, upload_to='sliders/%Y%m%d%s/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='slide',
            name='img_mob',
            field=models.ImageField(blank=True, upload_to='sliders/%Y%m%d%s/', verbose_name='Картинка для мобильных'),
        ),
    ]
