# Generated by Django 3.2.3 on 2025-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20250809_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='img',
            field=models.ImageField(blank=True, upload_to='sliders/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img_mob',
            field=models.ImageField(blank=True, upload_to='sliders/', verbose_name='Картинка для мобильных'),
        ),
    ]
