# Generated by Django 3.2.3 on 2025-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20250809_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img',
            field=models.ImageField(blank=True, upload_to='sliders/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img_mob',
            field=models.ImageField(blank=True, upload_to='sliders/%Y/%m/%d', verbose_name='Картинка для мобильных'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
    ]
