# Generated by Django 3.2.3 on 2025-08-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20250809_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='img',
            field=models.ImageField(upload_to='sliders/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
