# Generated by Django 3.2.3 on 2025-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_slide_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='icon',
            field=models.FileField(blank=True, upload_to='sliders/%Y/%m/%d', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='slide',
            name='img_tablet',
            field=models.ImageField(blank=True, upload_to='sliders/%Y/%m/%d', verbose_name='Картинка для планшетов'),
        ),
    ]
