# Generated by Django 3.2.3 on 2025-09-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
        ('page', '0014_alter_slide_img_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_img_ref', to=settings.CABINET_FILE_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img_tablet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_img_tablet_ref', to=settings.CABINET_FILE_MODEL, verbose_name='Картинка для планшетов'),
        ),
    ]
