# Generated by Django 3.2.3 on 2025-09-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
        ('page', '0015_auto_20250904_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_icon_ref', to=settings.CABINET_FILE_MODEL, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_img_ref', to=settings.CABINET_FILE_MODEL, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img_mob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_img_mobile_ref', to=settings.CABINET_FILE_MODEL, verbose_name='Картинка для мобильных'),
        ),
    ]
