# Generated by Django 3.2.3 on 2025-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
