# Generated by Django 3.2.3 on 2025-12-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_faq_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'FAQ'},
        ),
    ]
