# Generated by Django 3.2.3 on 2026-01-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_alter_faq_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'en'), ('ru', 'ru')], db_index=True, default='ru', max_length=10, verbose_name='Локаль (язык)')),
                ('context', models.CharField(blank=True, db_index=True, default='vrn', max_length=10, verbose_name='Контекст')),
                ('key', models.CharField(max_length=512, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'unique_together': {('locale', 'context', 'key')},
            },
        ),
    ]
