# Generated by Django 3.2.3 on 2022-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtask',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'Активна'), (1, 'Завершена')], default=0, verbose_name='Статус задачи'),
        ),
    ]
