# Generated by Django 3.2.3 on 2022-10-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_crmtask_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа задач',
                'verbose_name_plural': 'Группы задач',
            },
        ),
        migrations.AddField(
            model_name='crmtask',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.crmtaskgroup', verbose_name='Группа задач'),
        ),
    ]
