# Generated by Django 3.2.3 on 2021-08-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0017_auto_20210804_1603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баллов для списания')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Код')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.advertiser', verbose_name='Рекламодатель')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'СМС код',
                'verbose_name_plural': 'СМС коды',
                'ordering': ['-created_date'],
            },
        ),
    ]
