# Generated by Django 3.2.3 on 2021-06-16 12:16

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('logo_image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='advertiser_logo', verbose_name='Логотип')),
                ('short_description', models.CharField(default='', max_length=255, verbose_name='Короткое описание')),
                ('full_description', models.TextField(blank=True, default='', max_length=255, verbose_name='Полное описание')),
                ('award', models.IntegerField(default=0, verbose_name='Вознаграждение')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Рекламодатель',
                'verbose_name_plural': 'Рекламодатели',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('campaign_image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='campaign_image', verbose_name='Изображение акции')),
                ('short_description', models.CharField(default='', max_length=255, verbose_name='Короткое описание')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.advertiser', verbose_name='Рекламодатель')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-num'],
            },
        ),
    ]
