# Generated by Django 3.2.3 on 2021-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='short_description',
            field=models.TextField(default='', verbose_name='Короткое описание'),
        ),
    ]
