# Generated by Django 3.2.3 on 2021-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0002_auto_20210616_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='award',
            field=models.IntegerField(default=0, verbose_name='Вознаграждение'),
        ),
    ]
