# Generated by Django 3.2.3 on 2021-06-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='award',
        ),
    ]
