# Generated by Django 3.2.3 on 2021-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_advertiser_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={'ordering': ['num'], 'verbose_name': 'Рекламодатель', 'verbose_name_plural': 'Рекламодатели'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='quota',
            field=models.IntegerField(default=1, verbose_name='Квота участников'),
        ),
    ]
