# Generated by Django 3.2.3 on 2021-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_advertiser_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='company_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company_fio',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='ФИО контактного лица'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company_inn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ИНН компании'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo', verbose_name='Логотип компании'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование компании'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='kassir_login',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Логин кассира'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='kassir_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль кассира'),
        ),
    ]
