# Generated by Django 3.2.3 on 2021-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_advertiser_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
    ]
