# Generated by Django 3.2.3 on 2021-07-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210716_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='title',
        ),
    ]
