# Generated by Django 3.2.3 on 2021-07-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210716_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('payment_method', models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Robokassa')], default=0, verbose_name='Способ оплаты')),
                ('order_status', models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Новый'), (2, 'Оплачен'), (3, 'Отказ'), (4, 'Ошибка')], default=0, verbose_name='Статус счета')),
                ('summ', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.advertiser', verbose_name='Рекламодатель')),
            ],
            options={
                'verbose_name': 'Пополнение баланса',
                'verbose_name_plural': 'Пополнение баланса',
                'ordering': ['-edited_date'],
            },
        ),
    ]
