# Generated by Django 3.2.3 on 2021-07-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс акции'),
        ),
        migrations.CreateModel(
            name='Billing_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_increase', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Приход')),
                ('balance_decrease', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Расход')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс до корректировки')),
                ('balance_current', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс после корректировки')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата')),
                ('history_description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('change_type', models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение баланса'), (4, 'Списание за создание акции')], default=0, verbose_name='Тип')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История баланса',
                'verbose_name_plural': 'Изменения баланса',
                'ordering': ['edited_date'],
            },
        ),
    ]
