# Generated by Django 3.2.3 on 2021-07-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210719_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_history',
            name='user',
        ),
        migrations.AddField(
            model_name='billing_history',
            name='advertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.advertiser', verbose_name='Рекламодатель'),
            preserve_default=False,
        ),
    ]
