# Generated by Django 3.2.3 on 2021-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210720_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('sticking_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость оклейки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
