# Generated by Django 3.2.3 on 2021-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_advertisersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisersettings',
            name='period_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость периода'),
        ),
    ]
