# Generated by Django 3.2.3 on 2021-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_advertisersettings_period_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_history',
            name='change_type',
            field=models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение баланса'), (4, 'Списание за создание акции'), (5, 'Возврат не использованных средств')], default=0, verbose_name='Тип'),
        ),
    ]
