# Generated by Django 3.2.3 on 2021-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_billing_history_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='admin_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'На одобрении'), (2, 'Активна'), (3, 'Отклонена'), (4, 'Завершена'), (5, 'Удалена')], default=0, verbose_name='Статус акции'),
        ),
    ]
