# Generated by Django 3.2.3 on 2021-08-04 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0016_auto_20210802_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='kassir_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kassir_user_field', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь кассир'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='owner_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
