# Generated by Django 3.2.3 on 2021-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20210804_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approve_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата одобрения акции'),
        ),
    ]
