# Generated by Django 3.2.3 on 2021-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_campaign_approve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisersettings',
            name='logo_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость подготовки логотипа'),
        ),
    ]
