# Generated by Django 3.2.3 on 2021-08-27 10:04

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_advertisersettings_logo_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='logo_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='logo_campaign_image', verbose_name='Логотип акции'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sticker_text',
            field=models.TextField(default='', verbose_name='Текст наклейки'),
        ),
    ]
