# Generated by Django 3.2.3 on 2021-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20210827_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_history',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс до корректировки'),
        ),
        migrations.AlterField(
            model_name='billing_history',
            name='balance_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс после корректировки'),
        ),
        migrations.AlterField(
            model_name='billing_history',
            name='balance_decrease',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='billing_history',
            name='balance_increase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Приход'),
        ),
    ]
