# Generated by Django 3.2.3 on 2021-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20210831_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing_history',
            options={'ordering': ['-edited_date'], 'verbose_name': 'История баланса', 'verbose_name_plural': 'Изменения баланса'},
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company_legal_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Юридическое лицо'),
        ),
    ]
