# Generated by Django 3.2.3 on 2022-02-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_businesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.businesstype', verbose_name='Вид деятельности'),
        ),
    ]
