# Generated by Django 3.2.3 on 2022-05-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_advertiser_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='parent_business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.businesstype', verbose_name='Родительская категория'),
        ),
    ]
