# Generated by Django 3.2.3 on 2022-06-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_businesstype_parent_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_increase', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Приход')),
                ('balance_decrease', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Расход')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс до корректировки')),
                ('balance_current', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс после корректировки')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата')),
                ('history_description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('change_type', models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение при создании акции'), (4, 'Возврат не использованных средств на баланс рекламодателя')], default=0, verbose_name='Тип')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.advertiser', verbose_name='Рекламодатель')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.campaign', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'История баланса акции',
                'verbose_name_plural': 'Изменения баланса акции',
                'ordering': ['-edited_date'],
            },
        ),
    ]
