# Generated by Django 3.2.3 on 2022-06-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_campaignbalancehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing_history',
            options={'ordering': ['-edited_date'], 'verbose_name': 'История баланса компаний', 'verbose_name_plural': 'Изменения баланса компаний'},
        ),
        migrations.AlterField(
            model_name='campaignbalancehistory',
            name='change_type',
            field=models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение при создании акции'), (4, 'Возврат не использованных средств на баланс рекламодателя'), (5, 'Ежемесячное списание за бонусы для автовладельца')], default=0, verbose_name='Тип'),
        ),
    ]
