# Generated by Django 3.2.3 on 2022-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20220628_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignbalancehistory',
            name='change_type',
            field=models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение при создании акции'), (4, 'Возврат не использованных средств на баланс рекламодателя'), (5, 'Ежемесячное списание за пройденный период')], default=0, verbose_name='Тип'),
        ),
    ]
