# Generated by Django 3.2.3 on 2022-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_alter_campaignbalancehistory_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignbalancehistory',
            name='change_type',
            field=models.IntegerField(choices=[(0, 'Прочее'), (1, 'Корректировка'), (2, 'Отрицательная корректировка'), (3, 'Пополнение при создании акции'), (4, 'Возврат не использованных средств на баланс рекламодателя'), (5, 'Списание за одобренный фотоотчет'), (6, 'Списание за подготовку логотипа'), (7, 'Списание за оклейку автомобиля')], default=0, verbose_name='Тип'),
        ),
    ]
